[package]
name = "good_morning"
version = "0.1.0"
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
reqwest = "0.11"
futures = "0.3"
tokio = { version = "1.12.0", features = ["full"] }
json = "0.12"
colored = "2.0.0"
